// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Data.EF;

namespace WebAPI.Data.Migrations
{
    [DbContext(typeof(WebApiDbContext))]
    partial class WebApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de"),
                            RoleId = new Guid("8d04dce2-969a-435d-bba4-df3f325983dc")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("WebAPI.Data.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("WebAPI.Data.Entities.Category", b =>
                {
                    b.Property<int>("idCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("IsShowOnHome")
                        .HasColumnType("bit");

                    b.Property<string>("LanguageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("idCategory");

                    b.HasIndex("LanguageId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            idCategory = 1,
                            IsShowOnHome = true,
                            SortOrder = 1
                        },
                        new
                        {
                            idCategory = 2,
                            IsShowOnHome = true,
                            SortOrder = 2
                        },
                        new
                        {
                            idCategory = 3,
                            IsShowOnHome = true,
                            SortOrder = 3
                        },
                        new
                        {
                            idCategory = 4,
                            IsShowOnHome = true,
                            SortOrder = 4
                        },
                        new
                        {
                            idCategory = 5,
                            IsShowOnHome = true,
                            SortOrder = 5
                        },
                        new
                        {
                            idCategory = 6,
                            IsShowOnHome = true,
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("WebAPI.Data.Entities.CategoryTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("LanguageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeoAlias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeoDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeoTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("productsProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("productsProductId");

                    b.ToTable("CategoryTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            LanguageId = "vi",
                            Name = "Áo nam",
                            SeoAlias = "ao-nam",
                            SeoDescription = "Sản phẩm áo thời trang nam",
                            SeoTitle = "Sản phẩm áo thời trang nam"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            LanguageId = "en",
                            Name = "Men Shirt",
                            SeoAlias = "men-shirt",
                            SeoDescription = "The shirt products for men",
                            SeoTitle = "The shirt products for men"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            LanguageId = "vi",
                            Name = "Áo nữ",
                            SeoAlias = "ao-nu",
                            SeoDescription = "Sản phẩm áo thời trang nữ",
                            SeoTitle = "Sản phẩm áo thời trang women"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            LanguageId = "en",
                            Name = "Women Shirt",
                            SeoAlias = "women-shirt",
                            SeoDescription = "The shirt products for women",
                            SeoTitle = "The shirt products for women"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            LanguageId = "vi",
                            Name = "Máy ảnh",
                            SeoAlias = "may-anh",
                            SeoDescription = "may anh",
                            SeoTitle = "may anh"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            LanguageId = "vi",
                            Name = "Giày",
                            SeoAlias = "giay",
                            SeoDescription = "giay nam",
                            SeoTitle = "giay nam"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 5,
                            LanguageId = "vi",
                            Name = "Quần nam",
                            SeoAlias = "quan-nam",
                            SeoDescription = "quan-nam",
                            SeoTitle = "quan-nam"
                        });
                });

            modelBuilder.Entity("WebAPI.Data.Entities.Language", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = "vi",
                            IsDefault = true,
                            Name = "Tiếng Việt"
                        },
                        new
                        {
                            Id = "en",
                            IsDefault = false,
                            Name = "English"
                        });
                });

            modelBuilder.Entity("WebAPI.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("LanguageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShipAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("usersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("usersId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WebAPI.Data.Entities.OrderDetail", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("WebAPI.Data.Entities.ProductInCategory", b =>
                {
                    b.Property<int>("idCategory")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("idCategory", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductInCategories");

                    b.HasData(
                        new
                        {
                            idCategory = 1,
                            ProductId = 1
                        },
                        new
                        {
                            idCategory = 1,
                            ProductId = 2
                        },
                        new
                        {
                            idCategory = 1,
                            ProductId = 3
                        },
                        new
                        {
                            idCategory = 1,
                            ProductId = 4
                        },
                        new
                        {
                            idCategory = 1,
                            ProductId = 5
                        },
                        new
                        {
                            idCategory = 1,
                            ProductId = 6
                        },
                        new
                        {
                            idCategory = 1,
                            ProductId = 7
                        },
                        new
                        {
                            idCategory = 1,
                            ProductId = 8
                        },
                        new
                        {
                            idCategory = 1,
                            ProductId = 9
                        },
                        new
                        {
                            idCategory = 1,
                            ProductId = 10
                        },
                        new
                        {
                            idCategory = 1,
                            ProductId = 11
                        });
                });

            modelBuilder.Entity("WebAPI.Data.Entities.Slide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Slides");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.",
                            Image = "/themes/images/carousel/1.png",
                            Name = "Second Thumbnail label",
                            SortOrder = 1,
                            Status = true,
                            Url = "#"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.",
                            Image = "/themes/images/carousel/2.png",
                            Name = "Second Thumbnail label",
                            SortOrder = 2,
                            Status = true,
                            Url = "#"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.",
                            Image = "/themes/images/carousel/3.png",
                            Name = "Second Thumbnail label",
                            SortOrder = 3,
                            Status = true,
                            Url = "#"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.",
                            Image = "/themes/images/carousel/4.png",
                            Name = "Second Thumbnail label",
                            SortOrder = 4,
                            Status = true,
                            Url = "#"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.",
                            Image = "/themes/images/carousel/5.png",
                            Name = "Second Thumbnail label",
                            SortOrder = 5,
                            Status = true,
                            Url = "#"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.",
                            Image = "/themes/images/carousel/6.png",
                            Name = "Second Thumbnail label",
                            SortOrder = 6,
                            Status = true,
                            Url = "#"
                        });
                });

            modelBuilder.Entity("WebAPI.Data.Entities.productBrand", b =>
                {
                    b.Property<string>("idBrand")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("LanguageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("brandDetail")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("brandName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.HasKey("idBrand");

                    b.HasIndex("LanguageId");

                    b.ToTable("ProductBrands");

                    b.HasData(
                        new
                        {
                            idBrand = "1",
                            LanguageId = "vi",
                            brandDetail = "Logo",
                            brandName = "Logo"
                        },
                        new
                        {
                            idBrand = "2",
                            LanguageId = "vi",
                            brandDetail = "Company",
                            brandName = "Company"
                        });
                });

            modelBuilder.Entity("WebAPI.Data.Entities.productColor", b =>
                {
                    b.Property<string>("idColor")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("LanguageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("colorName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.HasKey("idColor");

                    b.HasIndex("LanguageId");

                    b.ToTable("ProductColors");

                    b.HasData(
                        new
                        {
                            idColor = "Red",
                            LanguageId = "vi",
                            colorName = "Red"
                        },
                        new
                        {
                            idColor = "While",
                            LanguageId = "vi",
                            colorName = "While"
                        });
                });

            modelBuilder.Entity("WebAPI.Data.Entities.productDetail", b =>
                {
                    b.Property<int>("idProductDetail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CategoryidCategory")
                        .HasColumnType("int");

                    b.Property<string>("LanguageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("detail")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(2000)");

                    b.Property<DateTime>("expiredSalingDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isSaling")
                        .HasColumnType("bit");

                    b.Property<string>("price")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<string>("salePrice")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(200)");

                    b.HasKey("idProductDetail");

                    b.HasIndex("CategoryidCategory");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ProductId");

                    b.ToTable("productDetails");

                    b.HasData(
                        new
                        {
                            idProductDetail = 1,
                            LanguageId = "vi",
                            ProductId = 1,
                            ProductName = "Ao nam",
                            dateAdded = new DateTime(2019, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            detail = "goood product",
                            expiredSalingDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isSaling = false,
                            price = "10",
                            salePrice = "10"
                        },
                        new
                        {
                            idProductDetail = 2,
                            LanguageId = "vi",
                            ProductId = 2,
                            ProductName = "Ao nam",
                            dateAdded = new DateTime(2019, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            detail = "goood product",
                            expiredSalingDate = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isSaling = false,
                            price = "20",
                            salePrice = "10"
                        },
                        new
                        {
                            idProductDetail = 3,
                            LanguageId = "vi",
                            ProductId = 3,
                            ProductName = "Ao nam",
                            dateAdded = new DateTime(2019, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            detail = "goood product",
                            expiredSalingDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isSaling = false,
                            price = "10",
                            salePrice = "10"
                        },
                        new
                        {
                            idProductDetail = 4,
                            LanguageId = "vi",
                            ProductId = 4,
                            ProductName = "Ao nam",
                            dateAdded = new DateTime(2019, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            detail = "goood product",
                            expiredSalingDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isSaling = false,
                            price = "10",
                            salePrice = "10"
                        },
                        new
                        {
                            idProductDetail = 5,
                            LanguageId = "vi",
                            ProductId = 5,
                            ProductName = "Ao nam",
                            dateAdded = new DateTime(2019, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            detail = "goood product",
                            expiredSalingDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isSaling = false,
                            price = "10",
                            salePrice = "10"
                        },
                        new
                        {
                            idProductDetail = 6,
                            LanguageId = "vi",
                            ProductId = 6,
                            ProductName = "Ao nam",
                            dateAdded = new DateTime(2019, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            detail = "goood product",
                            expiredSalingDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isSaling = false,
                            price = "10",
                            salePrice = "10"
                        },
                        new
                        {
                            idProductDetail = 7,
                            LanguageId = "vi",
                            ProductId = 7,
                            ProductName = "Ao nam",
                            dateAdded = new DateTime(2019, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            detail = "goood product",
                            expiredSalingDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isSaling = false,
                            price = "10",
                            salePrice = "10"
                        },
                        new
                        {
                            idProductDetail = 8,
                            LanguageId = "vi",
                            ProductId = 8,
                            ProductName = "Ao nam",
                            dateAdded = new DateTime(2019, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            detail = "goood product",
                            expiredSalingDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isSaling = false,
                            price = "10",
                            salePrice = "10"
                        },
                        new
                        {
                            idProductDetail = 9,
                            LanguageId = "vi",
                            ProductId = 9,
                            ProductName = "Ao nam",
                            dateAdded = new DateTime(2019, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            detail = "goood product",
                            expiredSalingDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isSaling = false,
                            price = "10",
                            salePrice = "10"
                        },
                        new
                        {
                            idProductDetail = 10,
                            LanguageId = "vi",
                            ProductId = 10,
                            ProductName = "Ao nam",
                            dateAdded = new DateTime(2019, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            detail = "goood product",
                            expiredSalingDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isSaling = false,
                            price = "10",
                            salePrice = "10"
                        },
                        new
                        {
                            idProductDetail = 11,
                            LanguageId = "vi",
                            ProductId = 11,
                            ProductName = "Ao nam",
                            dateAdded = new DateTime(2019, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            detail = "goood product",
                            expiredSalingDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isSaling = false,
                            price = "10",
                            salePrice = "10"
                        });
                });

            modelBuilder.Entity("WebAPI.Data.Entities.productPhotos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Caption")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("idProduct")
                        .HasColumnType("int");

                    b.Property<DateTime>("uploadedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("idProduct");

                    b.ToTable("productPhotos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Caption = "Thumbnail image",
                            FileSize = 53562L,
                            ImagePath = "/user-content/7d4eec52-45fa-4433-9465-46cf469805e8.jpg",
                            IsDefault = true,
                            SortOrder = 1,
                            idProduct = 1,
                            uploadedTime = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Caption = "Thumbnail image",
                            FileSize = 53562L,
                            ImagePath = "/user-content/7d4eec52-45fa-4433-9465-46cf469805e8.jpg",
                            IsDefault = true,
                            SortOrder = 2,
                            idProduct = 2,
                            uploadedTime = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Caption = "Thumbnail image",
                            FileSize = 53562L,
                            ImagePath = "/user-content/7d4eec52-45fa-4433-9465-46cf469805e8.jpg",
                            IsDefault = true,
                            SortOrder = 3,
                            idProduct = 3,
                            uploadedTime = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Caption = "Thumbnail image",
                            FileSize = 53562L,
                            ImagePath = "/user-content/7d4eec52-45fa-4433-9465-46cf469805e8.jpg",
                            IsDefault = true,
                            SortOrder = 4,
                            idProduct = 4,
                            uploadedTime = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Caption = "Thumbnail image",
                            FileSize = 53562L,
                            ImagePath = "/user-content/7d4eec52-45fa-4433-9465-46cf469805e8.jpg",
                            IsDefault = true,
                            SortOrder = 5,
                            idProduct = 5,
                            uploadedTime = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Caption = "Thumbnail image",
                            FileSize = 53562L,
                            ImagePath = "/user-content/7d4eec52-45fa-4433-9465-46cf469805e8.jpg",
                            IsDefault = true,
                            SortOrder = 6,
                            idProduct = 6,
                            uploadedTime = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Caption = "Thumbnail image",
                            FileSize = 53562L,
                            ImagePath = "/user-content/7d4eec52-45fa-4433-9465-46cf469805e8.jpg",
                            IsDefault = true,
                            SortOrder = 7,
                            idProduct = 7,
                            uploadedTime = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Caption = "Thumbnail image",
                            FileSize = 53562L,
                            ImagePath = "/user-content/7d4eec52-45fa-4433-9465-46cf469805e8.jpg",
                            IsDefault = true,
                            SortOrder = 7,
                            idProduct = 8,
                            uploadedTime = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Caption = "Thumbnail image",
                            FileSize = 53562L,
                            ImagePath = "/user-content/7d4eec52-45fa-4433-9465-46cf469805e8.jpg",
                            IsDefault = true,
                            SortOrder = 7,
                            idProduct = 9,
                            uploadedTime = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Caption = "Thumbnail image",
                            FileSize = 53562L,
                            ImagePath = "/user-content/7d4eec52-45fa-4433-9465-46cf469805e8.jpg",
                            IsDefault = true,
                            SortOrder = 7,
                            idProduct = 10,
                            uploadedTime = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Caption = "Thumbnail image",
                            FileSize = 53562L,
                            ImagePath = "/user-content/7d4eec52-45fa-4433-9465-46cf469805e8.jpg",
                            IsDefault = true,
                            SortOrder = 7,
                            idProduct = 11,
                            uploadedTime = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("WebAPI.Data.Entities.productSize", b =>
                {
                    b.Property<string>("idSize")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("LanguageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("sizeName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.HasKey("idSize");

                    b.HasIndex("LanguageId");

                    b.ToTable("ProductSizes");

                    b.HasData(
                        new
                        {
                            idSize = "L",
                            LanguageId = "vi",
                            sizeName = "L"
                        },
                        new
                        {
                            idSize = "M",
                            LanguageId = "vi",
                            sizeName = "M"
                        },
                        new
                        {
                            idSize = "XL",
                            LanguageId = "vi",
                            sizeName = "XL"
                        },
                        new
                        {
                            idSize = "XLL",
                            LanguageId = "vi",
                            sizeName = "XLL"
                        });
                });

            modelBuilder.Entity("WebAPI.Data.Entities.productTypes", b =>
                {
                    b.Property<string>("idType")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("LanguageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("typeName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.HasKey("idType");

                    b.HasIndex("LanguageId");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            idType = "VIP",
                            typeName = "Cao cấp"
                        },
                        new
                        {
                            idType = "NORMAL",
                            typeName = "Bình Thường"
                        });
                });

            modelBuilder.Entity("WebAPI.Data.Entities.products", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool?>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.Property<string>("idBrand")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("idColor")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("idSize")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("idType")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.HasKey("ProductId");

                    b.HasIndex("idBrand");

                    b.HasIndex("idColor");

                    b.HasIndex("idSize");

                    b.HasIndex("idType");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ViewCount = 0,
                            idBrand = "1",
                            idColor = "While",
                            idSize = "L",
                            idType = "VIP"
                        },
                        new
                        {
                            ProductId = 2,
                            ViewCount = 0,
                            idBrand = "1",
                            idColor = "While",
                            idSize = "L",
                            idType = "VIP"
                        },
                        new
                        {
                            ProductId = 3,
                            ViewCount = 0,
                            idBrand = "1",
                            idColor = "While",
                            idSize = "L",
                            idType = "VIP"
                        },
                        new
                        {
                            ProductId = 4,
                            ViewCount = 0,
                            idBrand = "1",
                            idColor = "While",
                            idSize = "L",
                            idType = "VIP"
                        },
                        new
                        {
                            ProductId = 5,
                            ViewCount = 0,
                            idBrand = "1",
                            idColor = "While",
                            idSize = "L",
                            idType = "VIP"
                        },
                        new
                        {
                            ProductId = 6,
                            ViewCount = 0,
                            idBrand = "1",
                            idColor = "While",
                            idSize = "L",
                            idType = "VIP"
                        },
                        new
                        {
                            ProductId = 7,
                            ViewCount = 0,
                            idBrand = "1",
                            idColor = "While",
                            idSize = "L",
                            idType = "VIP"
                        },
                        new
                        {
                            ProductId = 8,
                            ViewCount = 0,
                            idBrand = "1",
                            idColor = "While",
                            idSize = "L",
                            idType = "VIP"
                        },
                        new
                        {
                            ProductId = 9,
                            ViewCount = 0,
                            idBrand = "1",
                            idColor = "While",
                            idSize = "L",
                            idType = "VIP"
                        },
                        new
                        {
                            ProductId = 10,
                            ViewCount = 0,
                            idBrand = "1",
                            idColor = "While",
                            idSize = "L",
                            idType = "VIP"
                        },
                        new
                        {
                            ProductId = 11,
                            ViewCount = 0,
                            idBrand = "1",
                            idColor = "While",
                            idSize = "L",
                            idType = "VIP"
                        });
                });

            modelBuilder.Entity("WebAPI.Data.Entities.rating", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.Property<int?>("idProduct")
                        .HasColumnType("int");

                    b.Property<Guid>("idUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("rate")
                        .HasColumnType("int");

                    b.Property<DateTime>("rateDate")
                        .HasColumnType("datetime2");

                    b.HasIndex("idProduct");

                    b.HasIndex("idUser");

                    b.ToTable("ratings");
                });

            modelBuilder.Entity("WebAPI.Data.Entities.role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8d04dce2-969a-435d-bba4-df3f325983dc"),
                            ConcurrencyStamp = "6bad0467-cb6e-4859-a9b6-952a3855185c",
                            Description = "Administrator role",
                            Name = "admin",
                            NormalizedName = "admin"
                        });
                });

            modelBuilder.Entity("WebAPI.Data.Entities.users", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("birthday")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("interestedIn")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<DateTime>("lastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("note")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("province")
                        .HasColumnType("VARCHAR(200)");

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b310241e-46ef-4319-a026-680c703d81f8",
                            Email = "nhattruongtp2000@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "nhattruongtp2000@gmail.com",
                            NormalizedUserName = "admin",
                            PasswordHash = "AQAAAAEAACcQAAAAEDb5+2IEpdNULojnkwej4f/+GewwAiZxC2S/zJd9ypoyU9VvzQwxn+v2m/5NCTRI6g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin",
                            birthday = "2020-10-12 00:00:00",
                            firstName = "Nguyen",
                            lastLogin = new DateTime(2020, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            lastName = "Truong"
                        });
                });

            modelBuilder.Entity("WebAPI.Data.Entities.vouchers", b =>
                {
                    b.Property<string>("idVoucher")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<int>("isUse")
                        .HasColumnType("int");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.HasKey("idVoucher");

                    b.ToTable("vouchers");
                });

            modelBuilder.Entity("WebAPI.Data.Entities.Cart", b =>
                {
                    b.HasOne("WebAPI.Data.Entities.products", "Product")
                        .WithMany("Carts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI.Data.Entities.users", "AppUser")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebAPI.Data.Entities.Category", b =>
                {
                    b.HasOne("WebAPI.Data.Entities.Language", null)
                        .WithMany("Categories")
                        .HasForeignKey("LanguageId");
                });

            modelBuilder.Entity("WebAPI.Data.Entities.CategoryTranslation", b =>
                {
                    b.HasOne("WebAPI.Data.Entities.Category", "Category")
                        .WithMany("CategoryTranslations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI.Data.Entities.Language", "Language")
                        .WithMany("CategoryTranslations")
                        .HasForeignKey("LanguageId");

                    b.HasOne("WebAPI.Data.Entities.products", null)
                        .WithMany("CategoryTranslations")
                        .HasForeignKey("productsProductId");

                    b.Navigation("Category");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("WebAPI.Data.Entities.Order", b =>
                {
                    b.HasOne("WebAPI.Data.Entities.Language", "Language")
                        .WithMany("Orders")
                        .HasForeignKey("LanguageId");

                    b.HasOne("WebAPI.Data.Entities.users", null)
                        .WithMany("Orders")
                        .HasForeignKey("usersId");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("WebAPI.Data.Entities.OrderDetail", b =>
                {
                    b.HasOne("WebAPI.Data.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI.Data.Entities.products", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebAPI.Data.Entities.ProductInCategory", b =>
                {
                    b.HasOne("WebAPI.Data.Entities.products", "Product")
                        .WithMany("productInCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI.Data.Entities.Category", "Category")
                        .WithMany("productInCategories")
                        .HasForeignKey("idCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebAPI.Data.Entities.productBrand", b =>
                {
                    b.HasOne("WebAPI.Data.Entities.Language", "Language")
                        .WithMany("productBrands")
                        .HasForeignKey("LanguageId");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("WebAPI.Data.Entities.productColor", b =>
                {
                    b.HasOne("WebAPI.Data.Entities.Language", "Language")
                        .WithMany("productColors")
                        .HasForeignKey("LanguageId");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("WebAPI.Data.Entities.productDetail", b =>
                {
                    b.HasOne("WebAPI.Data.Entities.Category", null)
                        .WithMany("productDetails")
                        .HasForeignKey("CategoryidCategory");

                    b.HasOne("WebAPI.Data.Entities.Language", "Language")
                        .WithMany("productDetails")
                        .HasForeignKey("LanguageId");

                    b.HasOne("WebAPI.Data.Entities.products", "Products")
                        .WithMany("productDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebAPI.Data.Entities.productPhotos", b =>
                {
                    b.HasOne("WebAPI.Data.Entities.products", "Product")
                        .WithMany("productPhotos")
                        .HasForeignKey("idProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebAPI.Data.Entities.productSize", b =>
                {
                    b.HasOne("WebAPI.Data.Entities.Language", "Language")
                        .WithMany("ProductSizes")
                        .HasForeignKey("LanguageId");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("WebAPI.Data.Entities.productTypes", b =>
                {
                    b.HasOne("WebAPI.Data.Entities.Language", "Language")
                        .WithMany("productTypes")
                        .HasForeignKey("LanguageId");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("WebAPI.Data.Entities.products", b =>
                {
                    b.HasOne("WebAPI.Data.Entities.productBrand", "ProductBrand")
                        .WithMany("Products")
                        .HasForeignKey("idBrand")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI.Data.Entities.productColor", "ProductColor")
                        .WithMany("Products")
                        .HasForeignKey("idColor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI.Data.Entities.productSize", "ProductSize")
                        .WithMany("Products")
                        .HasForeignKey("idSize")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI.Data.Entities.productTypes", "ProductTypes")
                        .WithMany("Products")
                        .HasForeignKey("idType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductBrand");

                    b.Navigation("ProductColor");

                    b.Navigation("ProductSize");

                    b.Navigation("ProductTypes");
                });

            modelBuilder.Entity("WebAPI.Data.Entities.rating", b =>
                {
                    b.HasOne("WebAPI.Data.Entities.productDetail", "ProductDetail")
                        .WithMany()
                        .HasForeignKey("idProduct");

                    b.HasOne("WebAPI.Data.Entities.users", "Users")
                        .WithMany()
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductDetail");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("WebAPI.Data.Entities.Category", b =>
                {
                    b.Navigation("CategoryTranslations");

                    b.Navigation("productDetails");

                    b.Navigation("productInCategories");
                });

            modelBuilder.Entity("WebAPI.Data.Entities.Language", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("CategoryTranslations");

                    b.Navigation("Orders");

                    b.Navigation("productBrands");

                    b.Navigation("productColors");

                    b.Navigation("productDetails");

                    b.Navigation("ProductSizes");

                    b.Navigation("productTypes");
                });

            modelBuilder.Entity("WebAPI.Data.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("WebAPI.Data.Entities.productBrand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebAPI.Data.Entities.productColor", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebAPI.Data.Entities.productSize", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebAPI.Data.Entities.productTypes", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebAPI.Data.Entities.products", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("CategoryTranslations");

                    b.Navigation("OrderDetails");

                    b.Navigation("productDetails");

                    b.Navigation("productInCategories");

                    b.Navigation("productPhotos");
                });

            modelBuilder.Entity("WebAPI.Data.Entities.users", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
